vich_uploader:
    db_driver: orm

    mappings:
        actions:
            uri_prefix: /uploads/actions
            upload_destination: '%kernel.project_dir%/public/uploads/actions'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
