App\Entity\IndicatorValue:
  constraints:
    - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
        fields: [deployement, indicator]
        errorPath: indicator
        message: 'Un indicateur avec ce libellé existe déjà pour ce déploiement.'
  properties:
    taux1:
      - NotBlank: ~
      - LessThanOrEqual:
          value: 100
          message: 'le taux doit être inférieur à 100'
      - GreaterThanOrEqual:
          value: 0
          message: 'le taux doit être supérieur à 0'
    taux2:
      - NotBlank: ~
      - LessThanOrEqual:
          value: 10000
          message: 'le taux doit être inférieur à 1000'
      - GreaterThanOrEqual:
          value: 0
          message: 'le taux doit être supérieur à 0'
