App\Entity\Message:
  properties:
    name:
      - NotBlank: ~
      - Length:
          min: 3
          max: 30
          minMessage: 'Le nom "{{ value }}" doit avoir plus de 3 caractères'
          maxMessage: 'Le nom "{{ value }}" ne peut pas avoir plus de 30 caractères'
