App\Entity\Pole:
  constraints:
    - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
        fields: [axe, name]
        errorPath: name
        message: 'Le nom du pôle "{{ value }}" est déjà déclaré pour cet axe.'
  properties:
    name:
      - NotBlank: ~
      - Length:
          min: 3
          max: 100
          minMessage: 'Le nom "{{ value }}" doit avoir plus de 3 caractères'
          maxMessage: 'Le nom "{{ value }}" ne peut pas avoir plus de 100 caractères'
    taux1:
      - NotBlank: ~
      - LessThanOrEqual:
          value: 100
          message: 'le taux doit être inférieur à 100'
      - GreaterThanOrEqual:
          value: 0
          message: 'le taux doit être supérieur à 0'
    taux2:
      - NotBlank: ~
      - LessThanOrEqual:
          value: 10000
          message: 'le taux doit être inférieur à 10000'
      - GreaterThanOrEqual:
          value: 0
          message: 'le taux doit être supérieur à 0'
