monolog:
    handlers:
        main:
            type: fingers_crossed
            action_level: error
            handler: nested
            excluded_404s:
                # regex: exclude all 404 errors from the logs
                - ^/
        nested:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
        login:
            type:           rotating_file
            max_files:      15
            path:           "%kernel.logs_dir%/%kernel.environment%.auth.log"
            level:          info
            channels:       security
        main_error:
            type:           fingers_crossed
            action_level:   error
            handler:        streamed_error
        streamed_error:
            type:           rotating_file
            max_files:      15
            path:           "%kernel.logs_dir%/%kernel.environment%.error.log"
            level:          info
        main_critical:
            type:           fingers_crossed
            action_level:   critical
            handler:        grouped_critical
        grouped_critical:
            type:           group
            members:        ["streamed_critical","buffered_critical"]
        streamed_critical:
            type:           rotating_file
            max_files:      15
            path:           "%kernel.logs_dir%/%kernel.environment%.critical.log"
            level:          info
        buffered_critical:
            type:           buffer
            handler:        swift_critical
        swift_critical:
            type:           swift_mailer
            from_email:     emmanuel.sauvage@live.fr
            to_email:       emmanuel.sauvage@live.fr
            subject:        Une erreur critique est survenue !
            level:          info
